CREATE TABLE FILMLAND_USERS
(
   EMAIL_ID VARCHAR(255) NOT NULL,
   PASSWORD VARCHAR(255) NOT NULL,
   PRIMARY KEY(EMAIL_ID)
);


CREATE TABLE AVAILABLE_CATEGORIES
(
	CATEGORY_NAME VARCHAR(255) NOT NULL,
	PRICE INTEGER NOT NULL,
	REMAINING_COUNT INTEGER NOT NULL,
	PRIMARY KEY(CATEGORY_NAME)
);

CREATE TABLE USER_SUBSCRIBED_CATEGORIES
(
	SUBSCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL_ID VARCHAR(255) NOT NULL,
	CATEGORY_NAME VARCHAR(255) NOT NULL,
	REMAINING_CONTENT INTEGER NOT NULL,
	SUBSCRIPTION_START_DATE DATE,
	PRICE INTEGER NOT NULL,
	STATUS VARCHAR(1) DEFAULT 'Y',
	NEW_MEMBER VARCHAR(1) DEFAULT 'Y',
	PRIMARY KEY(SUBSCRIPTION_ID)
);

CREATE TABLE USER_SHARED_SUBSCRIPTION_CATEGORIES
(
	SHARED_SUBSCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL_ID_OWNER VARCHAR(255) NOT NULL,
	EMAIL_ID_SHARED_WITH VARCHAR(255) NOT NULL,
	SHARED_CATEGORY VARCHAR(255) NOT NULL, 
	PRIMARY KEY(SHARED_SUBSCRIPTION_ID)
)
