CREATE TABLE FILMLAND_USERS
(
   EMAIL_ID VARCHAR(255) NOT NULL,
   PASSWORD VARCHAR(30) NOT NULL,
   PRIMARY KEY(EMAIL_ID)
);


CREATE TABLE AVAILABLE_CATEGORIES
(
	CATEGORY_NAME VARCHAR(255) NOT NULL,
	PRICE INTEGER NOT NULL,
	REMAINING_COUNT INTEGER NOT NULL,
	PRIMARY KEY(CATEGORY_NAME)
);

CREATE TABLE USER_SUBSCRIBED_CATEGORIES
(
	SUBSCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL_ID VARCHAR(255) NOT NULL,
	CATEGORY_NAME VARCHAR(255) NOT NULL,
	REMAINING_CONTENT INTEGER NOT NULL,
	PRICE INTEGER NOT NULL,
	PRIMARY KEY(SUBSCRIPTION_ID)
)
